---
- name: Install rsync
  apt:
    pkg: rsync
    state: latest

- name: Create system user for replication rsync
  user:
    name: replicator
    system: yes

- name: Allow SSH key from replication slave
  authorized_key:
    user: replicator
    key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
