---
- name: install rsync
  apt:
    pkg: rsync
    state: latest

- name: generate keypair
  user:
    name: replicator
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: fetch public key
  fetch:
    dest: /tmp/
    flat: yes
    src: /home/replicator/.ssh/id_rsa.pub

- name: disable SSH host key checking
  lineinfile:
    dest: /home/replicator/.ssh/config
    line: "StrictHostKeyChecking no"
    create: yes
    state: present
    owner: replicator

- name: setup data disk
  filesystem:
    fstype: ext4
    device: /dev/vdb1

- name: create the data mountpoint
  file:
    path: /data
    state: directory
    owner: replicator

- name: mount data disk
  mount:
    name: /data
    src: /dev/vdb1
    state: mounted
    fstype: ext4

- name: create the target data directories
  file:
    path: "/data/{{ item }}"
    state: directory
    owner: replicator
  with_items:
    - database_snapshots
    - filesystem_snapshots
    - filesystem
    - database

- name: Set up cron entry for daily database snapshot
  cron:
    name: "Daily {{ item }} database snapshot"
    user: replicator
    special_time: daily
    job: /usr/bin/mysqldump -u root -B {{ item }} --dump-slave=1 | gzip > /data/database_snapshots/{{ item }}-`date +\%F`.sql.gz
  with_items:
    - "{{ databases }}"

- name: Set up cron entry for daily filesystem snapshot
  cron:
    name: "Daily filesystem snapshot"
    user: replicator
    special_time: daily
    job: /bin/tar czf /data/filesystem_snapshots/`date +\%F`.tar.gz /data/filesystem

- name: Set up hourly filesystem synchronization
  cron:
    name: "Hourly filesystem sync"
    user: replicator
    minute: 55
    hour: "0-5,7-23"
    job: /usr/bin/rsync -a --inplace --rsh='ssh' replicator@{{ nfs_host }}:/data/export/ /data/filesystem
